@baseUrl = http://localhost:5000/api

@token = 
### ========================================
### 1. AUTHENTICATION 
### ========================================

### 1A. Register New User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": " ",
    "email": " ",
    "password": " ",
    "role": "Admin" 
}

###

### 1B. Login User 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": " ",
    "password": " "
}

###

### 1C. Get Current Logged In User
GET {{baseUrl}}/auth/me
Authorization: Bearer (put your token)


### ========================================
### 2. FINANCIAL RECORDS
### ========================================

### 2A. Create a Record (only Admin)
POST {{baseUrl}}/records
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount": 50000,
    "type": "Income",
    "category": "Salary",
    "description": "Monthly salary credited"
}

###

### 2B. Get All Records (Admin & Analyst)
GET {{baseUrl}}/records?page=1&limit=10
Authorization: Bearer {{token}}

###

### 2C. Get Single Record by ID 
@recordId = PASTE_RECORD_ID_HERE
GET {{baseUrl}}/records/{{recordId}}
Authorization: Bearer {{token}}

###

### 2D. Update a Record (only Admin)
PUT {{baseUrl}}/records/{{recordId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount": 55000,
    "description": "Updated salary with bonus"
}

###

### 2E. Delete a Record (only Admin)
DELETE {{baseUrl}}/records/{{recordId}}
Authorization: Bearer {{token}}


### ========================================
### 3. DASHBOARD
### ========================================

### 3A. Get Dashboard Summary 
GET {{baseUrl}}/dashboard/summary
Authorization: Bearer {{token}}
